### ISSUE TITLE
As an admin I approve a claim before the funds of an issue are released to the solver

### ISSUE THREAD

**Issue by gerbert-vandenberghe** [FundRequest/platform#69] opened 2018-02-22 09:12 UTC
### Context

In a first phase the FundRequest administrators will verify the claims of fundings to see if they are allowed and to evaluate the usage of the FundRequest platform.

### Current flow of events

1. The resolver claims a funding.
2. The funds are transferred to the resolver.

### Desired flow of events

1. The resolver claims a funding.
2. The funding gets the status pending.
3. The system creates a claim with status pending.
3. The admin logs in on the admin console.
4. The admin sees an overview of claims with their status.
5. The admin verifies a claim.
6. If the claim is justified the admin approves the claim.
6.1. The funding is transferred to the resolver.
6.2. The funding gets the status rewarded; the claim gets the status approved.
6.3 The admin informs the funder and the resolver.

### Alternative flow

6. If the claim is not justified the admin declines the claim.
6.1. The funding stays on the issue with the status open; the claim gets the status declined.
6.2. The admin informs the resolver.

### Admin console

The admin console contains a sortable and filterable overview of claims. Default only open claims are displayed ordered on claim date ascending.

### Test cases
 
- Input: There is a bounty that is claimed, the admin logs in into the admin console.
   - Result: The admin sees the claim with status pending.
- Input: There is a bounty that is not claimed, the admin logs in into the admin console.
   - Result: The admin doesn't sees the claim.
- Input: There is a bounty for which the claim is declined, the admin logs in into the admin console.
   - Result: The admin sees the claim with status declined.
- Input: There is a bounty for which the claim is approved, the admin logs in into the admin console.
   - Result: The admin sees the claim with status approved.
- Input: The admin approves a claim.
   - Result: The bounty is paid out to the solver. The claim gets the status approved.
- Input: The admin declines a claim.
   - Result: The bounty is *not* paid out to the solver. The claim gets the status declined.

**Comment by karelstriegel** [comment] 2018-05-04 18:59
Only the pending is visible, once the issue is approved that request disappears in the admin console.

How do we make a denied claim visible to the claimer?

**Comment by nico-ptrs** [comment] 2018-05-09 13:34
Currently the status is put back to "Funded".
Is it necessary to do more? This shouldn't happen that much, the pull request of the issue should already be approved and merged, so this can only occur by improper use of our application.

**Closed** 2018-05-25 19:57 UTC
Labels: Core, Enhancement
